### PR TITLE
Implement template for the front end and automate browser reloading with gulp

### PR DESCRIPTION
**Pull request by desaawa**
#### What does this PR do?
Merges front end template for the app 
#### Description of Task to be completed?
Create the front end page with the corresponding css styles, and automate browser reloading with gulp.
#### How should this be manually tested?
Kindly view the files changed
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshots (if appropriate)
image

#### Questions:PR Naming
N/A

### CODE REVIEW

**Comment by q-ode** [comment]
Hi,

Can I see a mockup of how this would look?

**Comment by desaawa** [comment]
@q-ode I added a screenshot.

**Comment by q-ode** [comment]
Great Job!

The search however seems out of scope with the rest of the functionalities (i.e. `Create Index`, `Upload`).

It's also far away from the displayed result. It'll be too difficult to assume those functionalities go together.

**Comment by desaawa** [comment]
Hi @q-ode. I have moved the search closer.

**Pull request merged**
